var GAME_LEVELS = [
  ["x                                                                              x",
   "x                                                                              x",
   "x                                                                              x",
   "x                          o x                               x                 x",
   "x                         xx                                  xx               x",
   "x                     xxxx                                      xxxx           x",
   "x                  xx   xxxx        o        g         o      xxxx             x",
   "x                xx    x!!!!x      xxx      yyy       xxx    x!!!!x    o       x",
   "x          o          x!!!!!!x                              x!!!!!!x   xx      x",
   "x         xxx          x!!!!x              xxxxxx            x!!!!x            x",
   "x                         !!     xx      xxx!!!!xxx              v        g    x",
   "x     @        o           v             xx!!!!!!!!xx                    yy    x",
   "xxxxxxxx   xxxx               o      xx!!!!!!!!!!!xxx                    xx    x",
   "x                            xxx     x!!!!!!!!!!!!!!x     j              xx    x",
   "x               t                    xxx!!!!!!!!!!xxx    xxx             xx    x",
   "x            xxxx                      x!!xxxx!!xx                       xx    x",
   "x   g      j x  x                j            !!                 xxxxj   xx    x",
   "xxxyyyxxxxxxxx  xxxxxxxx !xxxxxxxxxxxxxxxxxxxx!!xxxxxx       xx xx  xxxxxxxxxxxx",
   "                       x!!x                  x!!x    x       xx!x               ",
   "                       x!!x                  xxxx    x       xx!x               ",
   "                       xxxx                          x       xxxx               ",
   "                                                     x!!!!!!!x                  ",
   "                                                     xxxxxxxxx                  ",
   "                                                                                "],
  ["x                                                                                                                x",
   "x                                                                                                                x",
   "x                                                                                                                x",
   "x                                                                                                                x",
   "x                 o                          xx  o     g xx                                                      x",
   "x                xxx                        xx  xx    yy   xx                     t                              x",
   "xt             xx!!!!=                    xx!!!!!!!!!!!!!!!!xx                 xxxxx!!!!!!xxxx                   x",
   "xxxx         xx!!!!!!xx       j           xx!!!!!!!!!!!!!!!!xx               xx                x=                x",
   "x         xxxxx!!!!!!xx    xxxxxxxx        x!!!!!!!!!!!!!!!!x              xx           g       xx               x",
   "x              xx!!!xx                      =!!!!!v!!!!!!!!x                                                     x",
   "xxxxx            xxx                         xxxxx !!vxxxxx         xxxx                                         x",
   "x   x j                                                                                                          x",
   "x   xxx                                                         t                                                x",
   "xxxxxxxxxx                                                   xxxxxxx              =xxy!!|!!!yxxx                 x",
   "x      xxxxxxxxx                     j                    j                       xxx!!!!!!!!xxx                 x",
   "x                                   xxx         o       xxxx=                       xx!!!!!!xx                   x",
   "x                o                             xxxx                                  xxxxxxxx                    x",
   "x          @  xxxxxxxx                  xxxxxxxx  xxxxxxxx                                                       x",
   "x        xxxxxx       t                                                                                          x",
   "x                     xx    xxxx            g                                                                    x",
   "x    g         xxxxxx  x       x  xxx                                                                            x",
   "x  xyyyxx  xxxxx       x       x                                                j       o       t                x",
   "x!!!x x!!!!!!x         x       x                                               xxxxxxxxxxxxxxxxxxx               x",
   "x!!!x x!!!!!!x         x!!!!!!!x                                      t                 g                        x",
   "x!!!x x!!!!!!x         x!!!!!!!x                                     xxxx                                j       x",
   "x!!!x x!!!!!!x         x!!!!!!!x                                                                        xxxx     x",
   "x!!!x x!!!!!!x         x!!!!!!!x   j                                                                          t  x",
   "x!!!x x!!!!!!x         x!!!!!!!xxxxxxxxy       yxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxyyyxxxxxxxxxx      xxxxxxxx",
   "x!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ",
   "xxxxx xxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],
  ["x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x      o                                                                         o                           x",
   "x     xxx                                                                       xxx                          x",
   "x       xxxx                                                                xxxx                             x",
   "x           xxxx                            g                           xxxx                                 x",
   "x  j           xxxxx  j                                         t  xxxxx                                     x",
   "x xxx               xxxx                                       xxxx                                          x",
   "x                        xxxx=                             =xxxx                                             x",
   "x              g                                                       g                                     x",
   "x  xxxxx     yyyy                      =xy    yx=                    yyyy                                    x",
   "x          xxx!!xxx                    x        x                  xxx!!xxx                                  x",
   "x         xxx!!!!xxx   xxxx            x        x                 xxx!!!!xxx                                 x",
   "x        xxx!!!!!!xxx                  x        x                xxx!!!!!!xxx                                x",
   "x         xxx!!!!xxx                   x        x     j    t      xxx!!!!xxx                                 x",
   "x          xxx!!xxx                    x        x    xxxxxxxxx     xxx!!xxx                                  x",
   "x            x!!x                      x        x                    x!!x            xx|xx                   x",
   "x             !!                t      x        x                     !!                                     x",
   "x             !!            xxxxx      x        x                     !!                                     x",
   "x  j  g       !!                       x        x             xxxxxx  !!                                     x",
   "x  xxyyyx     vv                        x   ||   x                    vv                                     x",
   "x                                      x!!!!!!!!x                           o                    t           x",
   "x                j                     x!!!!!!!!x                         xxxxx                xxxxx         x",
   "x       t       xxx                    x!!!!!!!!x                                                            x",
   "x       xxxxx                          x!!!!!!!!x      j                                                     x",
   "x                    j                 x!!!!!!!!x    xxxxxx                                                  x",
   "x                   xxx                x!!xxxx!!x                                                            x",
   "x                      xxx              !!    !!                                                             x",
   "x                         xxxx          vv    !!                                      g                      x",
   "x                                 g           !!                                    xyyyx                    x",
   "=                                yyy          vv            t                                                x",
   "x                             =xx                         xxxxxx                                             x",
   "x                          xxx                                                                               x",
   "x                       xxx                                                                                  x",
   "=                    xxx               j      g                                                              x",
   "x                 xxx                 xxxxxxxyyy                                                             x",
   "x        @     xxx                                                       j                      j            x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx    |xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                        yy    yy  yyyyyyyy  yy    yy      yy      yy  yy  yyyyyy  yy   yy                     ",
   "                        yy    yy  yyyyyyyy  yy    yy      yy      yy  yy  yyyyyy  yy   yy                     ",
   "                        yy    yy  yy    yy  yy    yy      yy      yy  yy  yy  yy  yy   yy                     ",
   "                        yy    yy  yy    yy  yy    yy      yy      yy  yy  yy  yy  yy   yy                     ",
   "                        yyyyyyyy  yy    yy  yy    yy      yy      yy  yy  yy  yy  yy   yy                     ",
   "                        yyyyyyyy  yy    yy  yy    yy      yy  yy  yy  yy  yy  yy  yy   yy                     ",
   "                           yy     yy    yy  yy    yy      yy  yy  yy  yy  yy  yy  yy   yy                     ",
   "                           yy     yy    yy  yy    yy      yy  yy  yy  yy  yy  yy  yy   yy                     ",
   "                           yy     yy    yy  yy    yy      yy  yy  yy  yy  yy  yy  yy   yy                     ",
   "                           yy     yyyyyyyy  yyyyyyyy      yyyyyyyyyy  yy  yy  yyyyyy                          ",
   "                           yy     yyyyyyyy  yyyyyyyy      yyyyyyyyyy  yy  yy  yyyyyy   gg                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
